### ISSUE TITLE
EPIC: Streaming Project [WIP]

### ISSUE THREAD

**Issue by failuer** [alloverse/open-planning#143]
### Planning
- [ ] Research
- [ ] Brainstorm
- [ ] Requirement Specification

### New Tech/Features
- [ ] [Twitch API Integration](Link) 
- [ ] [Single Mute](Link) 
- [ ] [Multi Mute] (Link)
- [ ] [Expanded Wrist Menu - ]()

### Environment
- [ ] [Stream Arena Design](Link) 
- [ ] [Skybox]()
- [ ] 

### New Apps
- [ ] [Stream Deck](Link) 

### Web:
- [ ] [Name](Link)
