### ISSUE TITLE
EPIC: Enable the collection of various Alloverse usage metrics

### ISSUE THREAD

**Issue by failuer** [alloverse/open-planning#58]
- [ ] [Recap: How far along are we?](https://github.com/alloverse/open-planning/issues/113)

### Net/Visor tracking
- [x] [Analytics collection proof-of-concept](https://github.com/alloverse/open-planning/issues/71)
- [ ] [Set up internal documentation in Notion re: Analytics tracking](https://github.com/alloverse/open-planning/issues/95) 
- [ ] [Set up a dashboard for tracking the analytics](https://github.com/alloverse/open-planning/issues/63)
- [ ] [Add the ability to track time spent in Alloverse per user](https://github.com/alloverse/open-planning/issues/64) (KR: "Have the Alloverse team spend at least 30% of working hours using Alloverse")
- [ ] [Add the ability to track when someone joins a place](https://github.com/alloverse/open-planning/issues/65) (KR: "Reach 20 monthly active users")
- [ ] [Track downloads with GA events on the downloads page](https://github.com/alloverse/open-planning/issues/70)
- [ ] Differentiate between users & apps for logging purposes

More trackable metrics TBD. Recurrence seems like a "product qualified lead", i.e. a user that returns to Alloverse were likely to have gotten something out of it and thus is a good match.

### Techy:
- [ ] [Setup logging endpoint (log.alloverse.com?)](https://github.com/alloverse/open-planning/issues/103)
- [ ] [Define log message structure](https://github.com/alloverse/open-planning/issues/104)
- [ ] [Figure out what sends what (does any system (allonet, alloui, ...) send anything automatically?)](https://github.com/alloverse/open-planning/issues/105)
- [ ] [Add log helpers to alloui](https://github.com/alloverse/open-planning/issues/106)

### Security: 
- [ ] [Only server sends data to logs.alloverse.com](https://github.com/alloverse/open-planning/issues/107)
- [ ] [Shared key in place secret envs sent as header to each log msg](https://github.com/alloverse/open-planning/issues/108)

### Web:
- [x] [Analyze where traffic to Alloverse.com is coming from](https://github.com/alloverse/open-planning/issues/84)

**Comment by Voxar** [comment]
Example of log payload from app to our endpoint (log.alloverse.com?)

session: We don't want to track users but it would be very valuable to correlate chains of events. Could use avatars entity id. 

Always contain: {
  app: string; name of the application sending the log, 
  version: string; semantic version of app. x.y.z.gsha, 
  session: string; anonymous user session identifier to map out a users interactions throughout the *verse,
  event: string; name of the log event, 
  data: table; additional data for the event, 
  timestamp: uint; gmt unix timestamp
}

{ "app": "allonet", "version": "1.2.3", "session": "kvatzzd", "event": "connected", "timestamp": 12312412312, "data": { "url": "arcade.places.alloverse.com" } }
{ "app": "allovisor", "version": 1.2.3", "session": "kvatzzd", "event": "button-tap", "timestamp": 12312412312, "data": { "button-id": "options" } }
{ "app": "allo-whiteboard", "version": 1.2.3", "session": "kvatzzd", "event": "button-tap", "timestamp": 12312412312, "data": { "button-id": "clear board" } }

**Comment by nevyn** [comment]
@Voxar Generate a tracking ID just so we can have a "unique users per month"? that is re-generated when reinstalling so we don't track across installs (for user's privacy).

since we have such low numbers, we'll just have to figure out a way to exclude ourselves from that number...

**Comment by nevyn** [comment]
there should be a plethora of B2B tools we could use too :)

**Comment by Voxar** [comment]
Security: 
- [ ] Only server sends data to logs.alloverse.com
- [ ] Shared key in place secret envs sent as header to each log msg
