### ISSUE TITLE
EPIC: Screensharing app

### ISSUE THREAD

**Issue by nevyn** [alloverse/open-planning#59]
[SC/1409](https://app.shortcut.com/alloverse/epic/1409): In order to have collaborative coding, we need to be able to mirror one's screen in VR.

- [ ] [Revive screensharing project - review what we already have](https://github.com/alloverse/screencap-test/issues/1)
- [ ] [Create a project for a Qt app](https://github.com/alloverse/allo-remotedesktop/issues/1)
- [ ] [Embed allonet and alloui in the Qt app](https://github.com/alloverse/allo-remotedesktop/issues/2)
- [ ] [2D UI: Configure which place to connect to](https://github.com/alloverse/allo-remotedesktop/issues/3)
- [ ] [2D UI: "Connect" checkbox](https://github.com/alloverse/allo-remotedesktop/issues/4)
- [ ] [2D UI: Status label](https://github.com/alloverse/allo-remotedesktop/issues/5)
- [ ] [Keep the Qt app connected for as long as the "connect" checkbox is checked](https://github.com/alloverse/allo-remotedesktop/issues/6)
- [ ] [VR UI: Toggle sharing, etc](https://github.com/alloverse/allo-remotedesktop/issues/7)
- [ ] [Bind it to a specific user, so not everybody can use its VR UI](https://github.com/alloverse/allo-remotedesktop/issues/8)
- [ ] [Build, CICD, functional for Mac](https://github.com/alloverse/allo-remotedesktop/issues/9)
- [ ] [Build, CICD, functional for Windows](https://github.com/alloverse/allo-remotedesktop/issues/10)
- [ ] [Build, CICD, functional for Linux](https://github.com/alloverse/allo-remotedesktop/issues/11)
