### ISSUE TITLE
EPIC: Screensharing nice-to-have

### ISSUE THREAD

**Issue by nevyn** [alloverse/open-planning#60]
[SH/2805](https://app.shortcut.com/alloverse/epic/2805)

- [ ] [Mac: Launch at boot](https://github.com/alloverse/allo-remotedesktop/issues/12)
- [ ] [Windows: Launch at boot](https://github.com/alloverse/allo-remotedesktop/issues/13)
- [ ] [Receive pointer and keyboard events](https://github.com/alloverse/allo-remotedesktop/issues/14)
- [ ] [Mac: Control cursor and keyboard](https://github.com/alloverse/allo-remotedesktop/issues/15)
- [ ] [Windows: Control cursor and keyboard](https://github.com/alloverse/allo-remotedesktop/issues/16)
- [ ] [Embed in visor](https://github.com/alloverse/allo-remotedesktop/issues/17)
