### ISSUE TITLE
EPIC: Create a generic, consistent style for AlloUI components

### ISSUE THREAD

**Issue by failuer** [alloverse/open-planning#61]
### Research/Feasibility
- [x] [Brainstorm UI](https://github.com/alloverse/alloui-lua/issues/3)
- [x] [Animate color change of button](https://github.com/alloverse/alloui-lua/issues/6)
- [x] [Animate size change of button](https://github.com/alloverse/alloui-lua/issues/7)
- [x] [Automatically resize the fileviewer canvas to fit the file to be displayed](https://github.com/alloverse/allo-fileviewer/issues/3)
- [x] [Update the title of the fileviewer title to match the filename when changing file](https://github.com/alloverse/allo-fileviewer/issues/4)
- [x] [Implement a 9patch-esque Surface with rounded corners](https://github.com/alloverse/alloui-lua/issues/29)

### General
- [x] [Define a AlloUI color palette](https://github.com/alloverse/alloui-lua/issues/9)
- [ ] [Define AlloUI typography guidelines](https://github.com/alloverse/alloui-lua/issues/8)

### Component design specification
- [x] [Design the Button component](https://github.com/alloverse/alloui-lua/issues/4)
- [x] [Design the Text Input component](https://github.com/alloverse/alloui-lua/issues/10)
- [x] [Design the Slider component](https://github.com/alloverse/alloui-lua/issues/13)
- [x] [Design the ResizeHandle component](https://github.com/alloverse/alloui-lua/issues/15)
- [ ] [Design the NavStack component](https://github.com/alloverse/alloui-lua/issues/16)
- [ ] [Design the TabView component](https://github.com/alloverse/alloui-lua/issues/19)
- [ ] (optional) [Design a Pagination component](https://github.com/alloverse/alloui-lua/issues/21)

### Component design implementation
- [ ] [Implement the Button component design specification](https://github.com/alloverse/alloui-lua/issues/12)
- [ ] [Implement the Text Input component design specification](https://github.com/alloverse/alloui-lua/issues/11)
- [ ] [Implement the Slider component design specification](https://github.com/alloverse/alloui-lua/issues/14)
- [ ] [Implement the ResizeHandle component design specification](https://github.com/alloverse/alloui-lua/issues/15)
- [ ] [Implement the NavStack component design specification](https://github.com/alloverse/alloui-lua/issues/20)
- [ ] [Implement a 9patch-esque Surface with rounded corners](https://github.com/alloverse/alloui-lua/issues/29)

**Comment by dmjezewska** [comment]
https://developer.oculus.com/resources/bp-rendering/ leaving it here for reference
