### ISSUE TITLE
EPIC: Improved layout tools for AlloUI

### ISSUE THREAD

**Issue by failuer** [alloverse/open-planning#62]
- [ ] [Implement "CSS-like" Margins & Paddings to StackView](https://github.com/alloverse/alloui-lua/issues/22)
- [ ] [Automatically run layout() in StackView as soon as something is added or removed from it](https://github.com/alloverse/alloui-lua/issues/23)
- [ ] [Implement StackView "gap" property which defines a static distance between children of the view](https://github.com/alloverse/alloui-lua/issues/24)
- [ ] [StackView: When adding things with addSubview, add them from left-to-right or top-to-bottom. (currently, it's right-to-left and bottom-to-top)](https://github.com/alloverse/alloui-lua/issues/31)
- [ ] [StackView: Add the addSubviewAt(number) method, allowing users to specify where a new item should be added.](https://github.com/alloverse/alloui-lua/issues/32)
- [ ] [StackView: In the constructor, add the option to reverse the order in which things are added.](https://github.com/alloverse/alloui-lua/issues/33)
- [ ] (optional) TBD
