### ISSUE TITLE
Create GitHub Milestones, epics, issues and tasks for Milestone 2022 Q2Q3

### ISSUE THREAD

**Issue by failuer** [alloverse/open-planning#66]
- [x] [EPIC: Enable the collection of various Alloverse usage metrics](https://github.com/alloverse/management/issues/58)
- [x] [EPIC: Create a generic, consistent style for AlloUI components](https://github.com/alloverse/management/issues/61)
- [x] [EPIC: Improved layout tools for AlloUI](https://github.com/alloverse/management/issues/62)
- [x] [EPIC: 2022 Q2Q3 Performance Improvements](https://github.com/alloverse/management/issues/67)
- [ ] [EPIC: Screensharing app](https://github.com/alloverse/management/issues/59)
- [ ] [EPIC: Screensharing nice-to-have](https://github.com/alloverse/management/issues/60)
