### ISSUE TITLE
EPIC: 2022 Q2Q3 Performance Improvements

### ISSUE THREAD

**Issue by failuer** [alloverse/open-planning#67]
- [x] https://github.com/alloverse/allonet/issues/25
- [x] _https://github.com/alloverse/allonet/issues/24_ -- dropped
- [ ] https://github.com/alloverse/allonet/issues/35
