### ISSUE TITLE
Set up internal documentation in Notion re: Analytics tracking

### ISSUE THREAD

**Issue by failuer** [alloverse/open-planning#95]
Purpose: How can we, internally, get access to our important metrics?

- [ ] Set up a page structure skeleton
- [ ] Figure out how/where to access the analytics data
- [ ] Set up a biweekly time slot where new data is being moved from wherever it can be accessed to the Notion pages.
